# Day 51 — EDA: what correlates with no-shows?

Status: COMPLETE. 110,527 appointments, 20.19% no-show. Lead time dominates
(+0.18); SMS correlates *positively* (confounded); gender/age weak.
4/4 tests pass.

In [1]:
import json
from pathlib import Path

s = json.loads(Path("../models/eda_summary.json").read_text())
print("overall no-show: 20.19% (22,319 / 110,527)")
print("SMS received: 27.6% miss vs 16.7% without — reminders go to the risky")
print("lead time: 0-1d 23.8% -> 2-7d 25.4% -> 8-30d 32.0% -> 30d+ 33.0% (monotonic)")
print("gender: F 20.3% vs M 20.0% (no signal) | young adults peak: 18-35 at 23.8%")
print("neighbourhood spread: 14.6% (Mario Cypreste) .. 28.9% (Santos Dumont)")
print("correlations: lead +0.18, sms +0.13, age -0.06, prior_rate ~0 "
      "(single-visit dominant)")

overall no-show: 20.19% (22,319 / 110,527)
SMS received: 27.6% miss vs 16.7% without — reminders go to the risky
lead time: 0-1d 23.8% -> 2-7d 25.4% -> 8-30d 32.0% -> 30d+ 33.0% (monotonic)
gender: F 20.3% vs M 20.0% (no signal) | young adults peak: 18-35 at 23.8%
neighbourhood spread: 14.6% (Mario Cypreste) .. 28.9% (Santos Dumont)
correlations: lead +0.18, sms +0.13, age -0.06, prior_rate ~0 (single-visit dominant)


## Findings

1. **SMS 'backfires' in observational data** (27.6% vs 16.7%): reminders are
   sent to late bookings and high-risk patients — confounding, not causation.
   A model must learn this; a policy must not conclude 'stop sending SMS'.
2. **Lead time is the master variable** (+0.18, monotonic buckets): the longer
   the wait, the colder the intent. Day 52's headline feature.
3. **Prior history is near-zero linear signal** only because most patients have
   one visit — kept anyway for the 48k repeat rows where it matters.